server:
  port: 8080

spring:
  application:
    name: spring-security-keycloak

  security:
    oauth2:
      client:
        # GOOGLE AS AUTH SERVER
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://${HOST}:9090/realms/beck

      resourceserver:
        jwt:
          issuer-uri: http://${HOST}:9090/realms/beck


      # GOOGLE AS AUTH SERVER
#      registration:
#        google:
#          client-id: ${CLIENT_ID}
#          client-secret: ${CLIENT_SECRET}
#
#        resourceserver:
#          jwt:
#            issuer-uri: https://accounts.google.com